apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      serverpod: deployment
  template:
    metadata:
      labels:
        serverpod: deployment
    spec:
      containers:
        - name: service
          image: deployment-image:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 96Mi
          readinessProbe:
            httpGet:
              port: 8081
              path: /health/readiness
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              port: 8081
              path: /health/liveness
            initialDelaySeconds: 10
