apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../deployment

patches:
  - target:
      kind: Deployment
      name: deployment
    patch: |
      - op: replace
        path: /metadata/name
        value: my-other-service

images:
  - name: deployment-image
    newName: my-other-service
    newTag: 1.2.3
